# Generated by Django 5.0.4 on 2024-04-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30, verbose_name='نام کتاب')),
                ('author', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('isbn_code', models.CharField(max_length=25, verbose_name='شماره شابک')),
                ('category', models.CharField(max_length=25, verbose_name='شماره شابک')),
                ('cover_image', models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to='images/books_cover', verbose_name='تصویر کتاب')),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf/', verbose_name='فایل کتاب')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد موجود')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت کتاب')),
                ('is_forbidden', models.BooleanField(default=False, verbose_name='کتاب ممنوعه')),
            ],
            options={
                'verbose_name': 'کتاب ها',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
    ]
