# Generated by Django 5.0.4 on 2024-04-10 14:25

import bookstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_category_alter_books_book_name_remove_books_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='cover_image',
            field=models.ImageField(blank=True, default='default_cover.jpg', null=True, upload_to=bookstore.models.update_cover_filename, verbose_name='تصویر کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to=bookstore.models.update_book_filename, verbose_name='فایل کتاب'),
        ),
    ]
