# Generated by Django 5.0.4 on 2024-04-10 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_userinventory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinventory',
            options={'verbose_name': 'موجودی کاربران', 'verbose_name_plural': 'موجودی کاربران'},
        ),
    ]
