# Generated by Django 5.0.4 on 2024-04-10 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_userinventory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت کتاب')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='سفارش کنسل شده')),
                ('canceled_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان کنسل شدن سفارش')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookstore.books', verbose_name='کتاب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش ها',
                'verbose_name_plural': 'سفارش ها',
            },
        ),
        migrations.CreateModel(
            name='ChargeTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ شارژ')),
                ('otp_token', models.CharField(max_length=30, unique=True, verbose_name='توکن شارژ')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت توکن')),
                ('apply_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان اعمال شدن توکن')),
                ('is_used', models.BooleanField(default=False, verbose_name='توکن استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن ها',
                'verbose_name_plural': 'توکن ها',
            },
        ),
    ]
